stages:
- build
- deploy

variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

job_build:
  image: maven:3.8-openjdk-17
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests=true
  artifacts:
    name: "Maven artifacts from $CI_PROJECT_NAME on $CI_COMMIT_REF_SLUG"
    paths:
      - "**/target"
  only:
    - master


job_deploy:
  image: ubuntu:23.10
  stage: deploy
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install -y apt-utils && apt-get install -y sshpass
  script:
    - sshpass -p 'NomadTeam' scp -o StrictHostKeyChecking=no -rP 15888 ./target/auth.jar  public@7.tcp.eu.ngrok.io:/opt/docker/auth/auth.jar
    - sshpass -p 'NomadTeam' ssh -t -L 9000:localhost:9000 -p 15888 public@7.tcp.eu.ngrok.io "docker-compose -f /opt/docker/docker-compose.yml up -d --build auth"