server:
  port: 8086
  servlet:
    context-path: /auth

spring:
  profiles:
    active: ${SPRING_PROFILE:default}
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/test}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update



eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
